# Generated by Django 5.2.8 on 2025-12-14 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_alter_equipe_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('senha_hash', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição (se aplicável)')),
                ('coordenador_aprovador', models.ForeignKey(blank=True, help_text='Coordenador que aprovou/rejeitou a solicitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Cadastro',
                'verbose_name_plural': 'Solicitações de Cadastro',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
