# Generated by Django 4.2.7 on 2025-12-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_solicitacaocadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Função'),
        ),
    ]
