# Generated by Django 5.2.8 on 2025-12-19 18:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('cliente', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('papel', models.CharField(blank=True, help_text='Ex: Desenvolvedor Backend, Tester, etc.', max_length=100)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.projeto')),
            ],
            options={
                'verbose_name': 'Participação em Projeto',
                'verbose_name_plural': 'Participações em Projetos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('professor', 'Professor'), ('estudante', 'Estudante')], default='estudante', max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('funcao', models.CharField(blank=True, max_length=100, verbose_name='Função')),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence.', related_name='usuario_set', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='usuario_set', to='auth.permission', verbose_name='permissões de usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('senha_hash', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_rejeicao', models.TextField(blank=True, help_text='Motivo da rejeição (se aplicável)')),
                ('coordenador_aprovador', models.ForeignKey(blank=True, help_text='Coordenador que aprovou/rejeitou a solicitação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to='meuapp.usuario')),
            ],
            options={
                'verbose_name': 'Solicitação de Cadastro',
                'verbose_name_plural': 'Solicitações de Cadastro',
                'ordering': ['-data_solicitacao'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(related_name='projetos_participando', through='meuapp.ParticipacaoProjeto', to='meuapp.usuario'),
        ),
        migrations.AddField(
            model_name='participacaoprojeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.usuario'),
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='meuapp.projeto')),
                ('lider', models.OneToOneField(blank=True, help_text='Líder da equipe (cada usuário pode liderar no máximo uma equipe)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_liderada', to='meuapp.usuario')),
                ('membros', models.ManyToManyField(blank=True, related_name='equipes_participando', to='meuapp.usuario')),
            ],
            options={
                'verbose_name': 'Equipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['projeto', 'nome'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='participacaoprojeto',
            unique_together={('usuario', 'projeto')},
        ),
    ]
